import numpy as np
from abc import ABC, abstractmethod
from typing import List, Tuple, Any

class BasePreprocessor(ABC):
    """Abstract interface for spatial image pre-processing."""
    
    @abstractmethod
    def process(self, image: np.ndarray) -> np.ndarray:
        """
        Process the raw eye image to localize and normalize the iris.
        
        Args:
            image (np.ndarray): The raw grayscale input image.
            
        Returns:
            np.ndarray: The unwrapped, normalized rectangular iris image.
        """
        pass


class BaseFeatureExtractor(ABC):
    """Abstract interface for feature vector generation."""
    
    @abstractmethod
    def extract(self, normalized_iris: np.ndarray) -> np.ndarray:
        """
        Extract features from the normalized iris and flatten into a 1D vector.
        
        Args:
            normalized_iris (np.ndarray): The unwrapped rectangular iris image.
            
        Returns:
            np.ndarray: A flattened 1D feature vector.
        """
        pass


class BaseDictionaryBuilder(ABC):
    """Abstract interface for constructing the training dictionary matrix (A)."""
    
    @abstractmethod
    def build(
        self, 
        preprocessor: BasePreprocessor, 
        extractor: BaseFeatureExtractor, 
        image_paths: List[str], 
        labels: List[Any]
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Build the dictionary matrix A from a set of training images.
        
        Args:
            preprocessor (BasePreprocessor): An instantiated preprocessor object.
            extractor (BaseFeatureExtractor): An instantiated feature extractor object.
            image_paths (List[str]): File paths to the training images.
            labels (List[Any]): Corresponding subject identities for the images.
            
        Returns:
            Tuple[np.ndarray, np.ndarray]: 
                - The dictionary matrix A (2D array where each column is a feature vector).
                - An array mapping each column index to a specific subject label.
        """
        pass


class BaseSparseSolver(ABC):
    """Abstract interface for solving the basis pursuit optimization."""
    
    @abstractmethod
    def solve(self, dictionary: np.ndarray, test_vector: np.ndarray) -> np.ndarray:
        """
        Solve the L1 minimization problem to find the sparse representation.
        
        Args:
            dictionary (np.ndarray): The training dictionary matrix A.
            test_vector (np.ndarray): The feature vector y of the test image.
            
        Returns:
            np.ndarray: The sparse coefficient vector x.
        """
        pass


class BaseMatcher(ABC):
    """Abstract interface for final classification based on residuals."""
    
    @abstractmethod
    def match(
        self, 
        dictionary: np.ndarray, 
        test_vector: np.ndarray, 
        sparse_vector: np.ndarray, 
        labels: np.ndarray
    ) -> Any:
        """
        Determine the identity of the test image by calculating the reconstruction residual for each class.
        
        Args:
            dictionary (np.ndarray): The training dictionary matrix A.
            test_vector (np.ndarray): The feature vector y of the test image.
            sparse_vector (np.ndarray): The sparse coefficient vector x generated by the solver.
            labels (np.ndarray): The label mapping for each column in the dictionary.
            
        Returns:
            Any: The final matched identity/label.
        """
        pass